# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      # non-default
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        exclude: |
          (?x)^(
              .*.iss|
              .*.ps1|
              path/to/file.py
          )$
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ["--autofix"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.11.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: ["--color=always", "--external-sources"]
        types: ["executable", "file", "shell", "text"]
        exclude: |
          (?x)^(
              path/to/file.py
          )$
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
        args: ["--diff", "--indent", "2", "--binary-next-line", "--space-redirects", "--case-indent"]
        types: ["executable", "file", "shell", "text"]
        exclude: |
          (?x)^(
              path/to/file.py
          )$
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/amperser/proselint
    rev: 0.13.0
    hooks:
      - id: proselint
        types: ["asciidoc", "file", "non-executable", "plain-text", "text"]
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.4.0
    hooks:
      - id: cspell
        args: ["--locale", "en,en-US,de-DE"]
        exclude: |
          (?x)^(
              \.proselintrc.json|
              \.gitignore|
              \.pre-commit-config.yaml|
              cSpell_dict.txt|
              flatpak_list.adoc|
              steamos_controller_layouts.adoc|
              windows_installation/config/swicd_app_config.conf|
              windows_drivers/dl_windows_drivers.sh|
              windows_installation/config/Microsoft.PowerShell_profile.ps1|
              windows_installation/config/Microsoft.PowerShell_profile_steamdeck.ps1|
              windows_installation/config/swicd_app_config.json|
              windows_installation/mswindows_01powershell.ps1|
              windows_installation/mswindows_02setup_apps.json|
              windows_installation/mswindows_02setup_new.ps1|
              windows_installation/mswindows_02setup_reg.json|
              windows_installation/mswindows_03fixes.ps1|
              windows_installation/unattend.xml|
              path/to/file.py
          )$
